[extend]
useDefault = true

[[rules]]
id = "aws-access-key"

description = "AWS Access Key"

regex = '''(?i)(AKIA|ASIA|AIDA|AGPA)[0-9A-Z]{16}'''

tags = ["aws", "key"]

[allowlist]
description = "ignore mock UI files"

paths = [
  'Top\.png',
  '''projects/17-cicd-pippeline/gitleaks-test-secret\.txt''',
  '''projects/12-mask-app/mask-app/Dashboard/app\.js''',
  '''projects/12-mask-app/mask-app/DetectionRules/app\.js''',
  '''projects/12-mask-app/mask-app/DetectionRules/index\.html''',
  '''projects/12-mask-app/react/unified-mask-app/src/logo\.svg''',
  '''projects/12-mask-app/react/unified-mask-app/doc/fileRole'''
]
