#!/bin/bash

# 1. モジュールのインストール
apt update
apt install -y strongswan strongswan-swanctl charon-systemd frr

# 2. 設定ファイルの作成 (swanctl.conf)
cat <<EOF > /etc/swanctl/swanctl.conf
aaa
EOF

# 3. インターフェースとルーティング定義
# 起動時に実行されるよう、まずは即時反映
ip tunnel add vti-t1 local 172.16.0.223 remote 3.18.50.193 mode vti key 10
ip tunnel add vti-t2 local 172.16.0.223 remote 18.221.57.88 mode vti key 11

ip addr add 169.254.49.226/30 dev vti-t1
ip addr add 169.254.233.34/30 dev vti-t2

ip link set vti-t1 up
ip link set vti-t2 up

ip route add 169.254.49.224/30 dev vti-t1 table 220
ip route add 169.254.233.32/30 dev vti-t2 table 220

ip route add 10.0.1.0/24 dev vti-t1 table 220 metric 10
ip route add 10.0.1.0/24 dev vti-t2 table 220 metric 20

sysctl -w net.ipv4.conf.all.rp_filter=0

# 4. FRRの設定 (frr.conf を直接書き換え)
# bgpd デーモンを有効化
sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons

cat <<EOF > /etc/frr/frr.conf
frr version 8.1
frr defaults traditional
hostname $(hostname)
log syslog informational
!
router bgp 65000
 bgp router-id 169.254.49.226
 timers bgp 6 20
 neighbor 169.254.49.225 remote-as 64512
 neighbor 169.254.49.225 update-source 169.254.49.226
 neighbor 169.254.233.33 remote-as 64512
 neighbor 169.254.233.33 update-source 169.254.233.34
 !
 address-family ipv4 unicast
  network 169.254.49.224/30
  network 169.254.233.32/30
  redistribute connected
  neighbor 169.254.49.225 soft-reconfiguration inbound
  neighbor 169.254.49.225 route-map ALLOW_ALL in
  neighbor 169.254.49.225 route-map ALLOW_ALL out
  neighbor 169.254.233.33 soft-reconfiguration inbound
  neighbor 169.254.233.33 route-map ALLOW_ALL in
  neighbor 169.254.233.33 route-map ALLOW_ALL out
 exit-address-family
exit
!
ip prefix-list ANY seq 5 permit 0.0.0.0/0 le 32
!
route-map ALLOW_ALL permit 10
 match ip address prefix-list ANY
exit
!
line vty
!
EOF

# 5. サービスの再起動と有効化
systemctl enable strongswan-swanctl
systemctl restart strongswan-swanctl
systemctl enable frr
systemctl restart frr