apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        livenessProbe:
          httpGet:
            path: /        # 標準のNGINXなら / で応答します
            port: 80       # containerPortと同じ 80 に修正
          initialDelaySeconds: 10 # 起動時間を考慮して少し長めに
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /        # 標準のNGINXなら / で応答します
            port: 80       # containerPortと同じ 80 に修正
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: WELCOME_TEXT
          valueFrom:
            configMapKeyRef:
              name: nginx-message-config
              key: MY_MESSAGE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password # ←ここにインデントや改行が正しく入っているか確認