#/etc/strongswan.conf
#strongSwan（charon）の動作全体の設定。デバッグログの出力レベルなどを調整する際に使用します。

charon {
        load_modular = yes
        plugins {
                include strongswan.d/charon/*.conf
        }
}

include strongswan.d/*.conf
